// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVrt9a4boGUXq-pWTGEk2idkAkAfbm0VI',
    appId: '1:1001980510841:web:295c07696f98f8ecae4aa8',
    messagingSenderId: '1001980510841',
    projectId: 'lttbdd-83c66',
    authDomain: 'lttbdd-83c66.firebaseapp.com',
    storageBucket: 'lttbdd-83c66.firebasestorage.app',
    measurementId: 'G-V6EJGXB7W8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt8G7HzdvbWx6cbyi7YOHJQmvJ7Kg9_8Y',
    appId: '1:1001980510841:android:210fa63822322331ae4aa8',
    messagingSenderId: '1001980510841',
    projectId: 'lttbdd-83c66',
    storageBucket: 'lttbdd-83c66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYHgSsm6LDlr8Q3N3opRtEngAsF4jDV1w',
    appId: '1:1001980510841:ios:b02295caf410fff3ae4aa8',
    messagingSenderId: '1001980510841',
    projectId: 'lttbdd-83c66',
    storageBucket: 'lttbdd-83c66.firebasestorage.app',
    iosBundleId: 'com.example.lttbdd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYHgSsm6LDlr8Q3N3opRtEngAsF4jDV1w',
    appId: '1:1001980510841:ios:b02295caf410fff3ae4aa8',
    messagingSenderId: '1001980510841',
    projectId: 'lttbdd-83c66',
    storageBucket: 'lttbdd-83c66.firebasestorage.app',
    iosBundleId: 'com.example.lttbdd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVrt9a4boGUXq-pWTGEk2idkAkAfbm0VI',
    appId: '1:1001980510841:web:aacef6fd210cae87ae4aa8',
    messagingSenderId: '1001980510841',
    projectId: 'lttbdd-83c66',
    authDomain: 'lttbdd-83c66.firebaseapp.com',
    storageBucket: 'lttbdd-83c66.firebasestorage.app',
    measurementId: 'G-BX4FDPX6V2',
  );
}
