// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3iMdSFjrr-VVJWA3IKApwhvMjpSZUkCg',
    appId: '1:265379010052:web:f3fddb669946aee4df0751',
    messagingSenderId: '265379010052',
    projectId: 'hutech-ac20a',
    authDomain: 'hutech-ac20a.firebaseapp.com',
    databaseURL: 'https://hutech-ac20a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hutech-ac20a.firebasestorage.app',
    measurementId: 'G-EK1937EXTZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeGSti7p0pZnwxmSl_2ZmtVz6mpDjYvjk',
    appId: '1:265379010052:android:545363415dfa53b4df0751',
    messagingSenderId: '265379010052',
    projectId: 'hutech-ac20a',
    databaseURL: 'https://hutech-ac20a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hutech-ac20a.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_AzHhRNf8uEmMdZ1ZQsnoDcBfnYGsJ1Y',
    appId: '1:265379010052:ios:553ef64b543f68efdf0751',
    messagingSenderId: '265379010052',
    projectId: 'hutech-ac20a',
    databaseURL: 'https://hutech-ac20a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hutech-ac20a.firebasestorage.app',
    iosBundleId: 'com.example.vietsecurities',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_AzHhRNf8uEmMdZ1ZQsnoDcBfnYGsJ1Y',
    appId: '1:265379010052:ios:553ef64b543f68efdf0751',
    messagingSenderId: '265379010052',
    projectId: 'hutech-ac20a',
    databaseURL: 'https://hutech-ac20a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hutech-ac20a.firebasestorage.app',
    iosBundleId: 'com.example.vietsecurities',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3iMdSFjrr-VVJWA3IKApwhvMjpSZUkCg',
    appId: '1:265379010052:web:300fb27fab024626df0751',
    messagingSenderId: '265379010052',
    projectId: 'hutech-ac20a',
    authDomain: 'hutech-ac20a.firebaseapp.com',
    databaseURL: 'https://hutech-ac20a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hutech-ac20a.firebasestorage.app',
    measurementId: 'G-HXK2BMEGD5',
  );
}
